version: '3'
services:
  # MongoDB service (for access use `mongosh --username db_user` in terminal)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./express-api/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_s3cur3p4sswd
      MONGO_INITDB_DATABASE: supplier_service

  # Express.js API service to store supplier
  express-api:
    build:
      context: ./express-api
    container_name: express-api
    volumes:
      - ./express-api:/opt/project # Mount the app code (local:container)
      - /opt/project/node_modules/
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://supplier_service_user:supersecure@mongodb:27017/supplier_service
      NODE_ENV: dev
      DEBUG: ctl

  # React app to see supplier
  react-app:
    build:
      context: ./react-app
    container_name: react-app
    ports:
      - '3000:3000'
    depends_on:
      - express-api
    volumes:
      - ./react-app:/opt/project # Mount the app code (local:container)
      - /opt/project/node_modules/
    environment:
      PUBLIC_URL: http://localhost:3000
      NODE_ENV: dev

volumes:
  mongodb_data: