import React from "react"
import { Providers } from '@/lib/providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <Providers>
          <html className="h-full bg-white" lang="en">
            <body className={[inter.className].concat(["h-full"]).join(" ")}>
                {children}
            </body>
          </html>
      </Providers>
  )
}
